### ISSUE TITLE
Source code?

### ISSUE THREAD

**Issue by Max-Fu** [ShujaKhalid/polyrnn-pp#1]
Hello,

Thank you for implementing polygon-rnn++. I am quite curious where is the source code of this line 
`models.official.resnet` In addition, can you point out how this implementation includes atrous convolution? 

Thanks!

**Comment by ShujaKhalid** [comment]
Hey Max, 

The resnet code has been extracted from tensorflows official resnet library. You can find it here:

https://github.com/tensorflow/models/tree/master/official/resnet

As for the rest of the code, it is a work in progress and unfortunately, I have not been able to find the time to push it to its completion. There are still quite a few features that need to be tested before having a trainable model.

I intend on getting to it sooner rather than later.

Best,
Shuja

**Comment by Max-Fu** [comment]
Hello,

Thanks. So the CNN part is trained first on CIFAR? Not directly Cityscapes? I am quite confused by the paper itself because cityscape requires either to crop or an object detection/localization mechanism such as faster rcnn (mentioned later in the paper without much detail).

Can you also point out (if you have worked through this part) how this implementation put forth 
![image](https://user-images.githubusercontent.com/17964817/41815202-1d632224-7796-11e8-95db-82789c2deb41.png)? The original paper mentions but does not include the new stride and dilation factors that they applied to the ResNet architecture. 

Best, 
Max

**Comment by Max-Fu** [comment]
The original quote is 

> In order to alleviate this issue, we follow [7] and modify the ResNet-50 architecture [13] by reducing the stride of the network and introducing dilation factors.

on page 2, 3.1 of the paper. 

Best, 
Max

**Comment by Max-Fu** [comment]
Hi Shuja,

Thank you for your response, I think I have solved my issue. I will just close this issue. 

Best,
Max
